// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/teacher-profile/Profile.tsx": () => import("../components/mockups/teacher-profile/Profile.tsx"),
  "./components/mockups/teacher-progress/Progress.tsx": () => import("../components/mockups/teacher-progress/Progress.tsx"),
  "./components/mockups/teacher-dashboard/ActivityFeed.tsx": () => import("../components/mockups/teacher-dashboard/ActivityFeed.tsx"),
  "./components/mockups/teacher-dashboard/CommandCenter.tsx": () => import("../components/mockups/teacher-dashboard/CommandCenter.tsx"),
  "./components/mockups/teacher-dashboard/StudentPulse.tsx": () => import("../components/mockups/teacher-dashboard/StudentPulse.tsx"),
  "./components/mockups/teacher-results/Results.tsx": () => import("../components/mockups/teacher-results/Results.tsx")
};
