// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/teacher-progress/Progress.tsx": () => import("../components/mockups/teacher-progress/Progress.tsx"),
  "./components/mockups/teacher-results/Results.tsx": () => import("../components/mockups/teacher-results/Results.tsx")
};
